function Get-HtmlReportFooter {

    param (

        # Stopwatch that was started when report generation began
        [System.Diagnostics.Stopwatch]$StopWatch,

        # NT Account caption (CONTOSO\User) of the account running this function
        [String]$WhoAmI = (whoami.EXE),

        <#
        FQDN of the computer running this function

        Can be provided as a string to avoid calls to HOSTNAME.EXE and [System.Net.Dns]::GetHostByName()
        #>
        [String]$ThisFqdn = ([System.Net.Dns]::GetHostByName((HOSTNAME.EXE)).HostName),

        [uint64]$TargetCount,
        [uint64]$ParentCount,
        [uint64]$ChildCount,
        [uint64]$ItemCount,
        [uint64]$FqdnCount,
        [uint64]$AclCount,
        [uint64]$AceCount,
        [uint64]$IdCount,
        [UInt64]$PrincipalCount,
        [uint64]$FormattedPermissionCount,

        [uint64]$TotalBytes,

        [String]$ReportInstanceId,

        [UInt64]$PermissionCount,

        [string[]]$UnitsToResolve = @('day', 'hour', 'minute', 'second')

    )

    $null = $StopWatch.Stop()
    $FinishTime = Get-Date
    $StartTime = $FinishTime.AddTicks(-$StopWatch.ElapsedTicks)
    $TimeZoneName = Get-TimeZoneName -Time $FinishTime
    $Duration = Format-TimeSpan -TimeSpan $StopWatch.Elapsed -UnitsToResolve $UnitsToResolve

    if ($TotalBytes) {
        $TiB = $TotalBytes / 1TB
        $Size = " ($TiB TiB"
    }

    $CompletionTime = @(
        @{
            'Name'              = 'Target paths'
            'Count'             = $TargetCount
            'Average Time Each' = $Duration / $TargetCount
        },
        @{
            'Name'              = 'Parent paths'
            'Count'             = $ParentCount
            'Average Time Each' = $Duration / $ParentCount
        },
        @{
            'Name'              = 'Child paths'
            'Count'             = $ChildCount
            'Average Time Each' = $Duration / $ChildCount
        },
        @{
            'Name'              = 'Item paths (parents and children)'
            'Count'             = $ItemCount
            'Average Time Each' = $Duration / $ItemCount
        },
        @{
            'Name'              = 'Item servers'
            'Count'             = $FqdnCount
            'Average Time Each' = $Duration / $FqdnCount
        },
        @{
            'Name'              = 'ACLs'
            'Count'             = $AclCount
            'Average Time Each' = $Duration / $AclCount
        },
        @{
            'Name'              = 'ACEs'
            'Count'             = $AceCount
            'Average Time Each' = $Duration / $AceCount
        },
        @{
            'Name'              = 'IDs'
            'Count'             = $IdCount
            'Average Time Each' = $Duration / $IdCount
        },
        @{
            'Name'              = 'Security Principals'
            'Count'             = $PrincipalCount
            'Average Time Each' = $Duration / $PrincipalCount
        },
        @{
            'Name'              = 'Grouped and Expanded Permissions'
            'Count'             = $PrincipalCount
            'Average Time Each' = $Duration / $PermissionCount
        },
        @{
            'Name'              = 'Formatted Permissions'
            'Count'             = $PrincipalCount
            'Average Time Each' = $Duration / $FormattedPermissionCount
        },
        @{
            'Name'              = 'Data Size'
            'Count'             = $TiB
            'Average Time Each' = $Duration / $TiB
        },
        @{
            'Name'              = 'TOTAL'
            'Count'             = 1
            'Average Time Each' = $Duration
        }
    )

    $Heading = New-HtmlHeading 'Performance' -Level 6
    $Html = $CompletionTime | ConvertTo-Html -Fragment
    $Table = $Html | New-BootstrapTable
    New-BootstrapDiv -Text ($Heading + $Table) -Class 'h-100 p-1 bg-light border rounded-3 table-responsive'

    $Text = @"
Report generated by $WhoAmI on $ThisFQDN starting at $StartTime and ending at $FinishTime $TimeZoneName (elapsed: $Duration)<br />
Report instance: $ReportInstanceId
"@

    New-BootstrapAlert -Class Light -Text $Text -AdditionalClasses ' small'

}
<#
$TagetPath.Count parent folders
$ItemCount total folders including children
$FolderPermissions folders with unique permissions
$Permissions.Count access control entries on those folders
$Identities.Count identities in those access control entries
$FormattedSecurityPrincipals principals represented by those identities
$UniqueAccountPermissions.Count unique accounts after filtering out any specified domain names
$ExpandedAccountPermissions.Count effective permissions belonging to those principals and applying to those folders
#>
